# Generated by Django 4.0.4 on 2022-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_tourists_delete_tourist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromC', models.CharField(max_length=100)),
                ('destC', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('guide', models.CharField(max_length=100)),
                ('gnum', models.CharField(max_length=100)),
            ],
        ),
    ]
